name: Nginx

on:
  push:
    branches: ["main"]
    tags: ["nginx/v*"]
  pull_request:
    branches: [main]
    paths: ["nginx/**"]
  schedule:
    - cron: "33 2 * * SUN"

jobs:
  build:
    uses: bsm/misc/.github/workflows/build-push-ghcr.yml@main
    with:
      image: ghcr.io/${{ github.repository }}/nginx
      context: nginx
      file: nginx/Dockerfile
      tags: |
        type=raw,value=1-alpine-slim,enable={{is_default_branch}}
